# Generated by Django 2.1.7 on 2019-03-19 10:30

from django.db import migrations, models
import djongo.models.fields
import picklefield.fields
import submission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('stream_name', djongo.models.fields.ArrayModelField(model_container=submission.models.Stream)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('results', picklefield.fields.PickledObjectField(default='Null', editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', djongo.models.fields.ArrayModelField(model_container=submission.models.Class)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=30)),
                ('classteacher', models.CharField(max_length=40)),
                ('exam', djongo.models.fields.ArrayModelField(model_container=submission.models.Exam)),
            ],
        ),
    ]
