# Generated by Django 2.1.7 on 2019-03-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_Number',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
