# Generated by Django 2.1.7 on 2019-03-19 10:40

from django.db import migrations
import djongo.models.fields
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_institution_institution_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='class_name',
            field=djongo.models.fields.ArrayModelField(default=1, model_container=submission.models.Class),
            preserve_default=False,
        ),
    ]
