# Generated by Django 2.1.7 on 2019-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_institution_class_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_Number',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
