# Generated by Django 2.1.7 on 2019-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20190319_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_Number',
            field=models.IntegerField(default=0),
        ),
    ]
