# Generated by Django 2.1.7 on 2019-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20190324_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=30)),
                ('Mathematics', models.CharField(max_length=20)),
                ('English', models.CharField(max_length=20)),
                ('Kiswahili', models.CharField(max_length=20)),
                ('Physics', models.CharField(max_length=20)),
                ('Chemistry', models.CharField(max_length=20)),
                ('Biology', models.CharField(max_length=20)),
                ('Geography', models.CharField(max_length=20)),
                ('History', models.CharField(max_length=20)),
                ('Business', models.CharField(max_length=20)),
                ('CRE', models.CharField(max_length=20)),
                ('French', models.CharField(max_length=20)),
            ],
        ),
    ]
