# Generated by Django 2.1.7 on 2019-04-04 15:35

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('results', picklefield.fields.PickledObjectField(default='Null', editable=False, null=True)),
            ],
        ),
    ]
