# Generated by Django 2.1.7 on 2019-04-16 12:55

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_customexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Biology',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Business',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='CRE',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Chemistry',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='English',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='French',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Geography',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='History',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Kiswahili',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Mathematics',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Physics',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_list',
            field=picklefield.fields.PickledObjectField(default='Null', editable=False),
        ),
    ]
